ttu-ttu/ebook-reader

src/app/theme-manager.service.ts, src/styles.scss
I personally find the current dark theme too strong in terms of contrast
PR adds a gray theme (same vars as dark, just a different background-color) similar to a color tone of the dark mode of the edge browser.
https://imgur.com/a/8EIfgMK
=> [feat] add grayish mode

src/app/theme-manager.service.ts, src/styles.scss
I've had a couple people ask for this and I also use an AMOLED device so I thought this would be pretty nifty to have for energy-saving.
I haven't compiled or tested this as I don't have an environment set up and just followed my intuition looking at how a theme was added in **#1** though.
=> [feature] Implement black theme for AMOLED devices

README.md, src/app/app.component.ts
Seems to be pretty snappy 😆
I guess an icon could be worth adding.
=> Add return to bookmark keyboard shortcut

src/app/utils/logger/logger.service.ts
=> fix: properly display dom error on log

package.json, pnpm-lock.yaml
=> chore: pin cypress

.dockerignore, Dockerfile, README.md, nginx/conf.d/default.conf
=> docs: create guide for local environment build

src/app/book-manager/book-manager.component.ts, src/app/settings/pure-settings-content/pure-settings-content.component.html, src/app/settings/pure-settings-content/pure-settings-content.component.ts, src/app/settings/settings-content/settings-content.component.html, src/app/settings/settings-content/settings-content.component.ts, src/app/store.service.ts
=> feat: request for persistent storage

apps/web/firebase.json, apps/web/src/service-worker.ts
Because 50ms response wasn't realistic from my testing, current goal is to make it work offline instead of loading it asap
=> Update cache method

apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte
Right now the behavior feels unnatural for rl view (have to scroll right to move forward)
=> fix: update wheel x scroll for rl view to follow flow direction

apps/web/src/lib/components/log-report-dialog.svelte
For debugging especially with viewport-sensitive bugs
=> feat: add more details to error report file

apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte, apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte, apps/web/src/lib/components/book-reader/book-reader.svelte, apps/web/src/lib/components/settings/settings-content.svelte, apps/web/src/lib/data/store.ts, apps/web/src/routes/b/index.svelte, apps/web/src/routes/settings/index.svelte
closes #13 
timing does not be configureable i guess - i put it to 3 seconds for now
=> feat: auto bookmark

apps/web/src/lib/data/store.ts
It may makes sense to have the Paginated View as Default as it performs better and potentially give new Users a better first impression of the Reader
=> refactor: make pagination to view mode default

apps/web/src/lib/components/popover/popover.svelte, apps/web/src/lib/components/settings/settings-content.svelte, apps/web/src/lib/components/settings/settings-dimension-content.svelte, apps/web/src/lib/components/settings/settings-dimension-popover.svelte, apps/web/src/lib/components/settings/settings-dimension-preset.svelte, apps/web/src/lib/components/settings/settings-item-group.svelte
Adds a helper Slider Popover to the dimension settings which lets the User choose % values of the available window height/width in the range from 0-50%/50-75%
https://renji-xd.github.io/ebook-reader/settings
=> feat: dimension settings helper

README.md, docker-compose.yml
- Added a docker-compose.yml file to ease the management of the project-image
- Adapted the README.md to give instructions about how to run the project using docker compose
=> Creation of docker-compose file

apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte, pnpm-lock.yaml
i read a comment about the bookmark highlighting being distracting in conjunction with the auto bookmark option.
PR replaces the highlight by the same bookmark icon used in the pagination mode. It will be displayed left or top on the reader content. Not sure if that is less distracting but at least the ux between the modes would be better aligned.
https://renji-xd.github.io/ebook-reader/
=> refactor: align continous bookmark with pagination ux

apps/web/src/service-worker.ts
To enable prerender cache on links like `/b?id=123` before F5 refresh on the specified ids
=> fix: use prerendered cache for url with params

apps/web/src/lib/components/book-reader/book-toc/book-toc.svelte, apps/web/src/routes/b/index.svelte
closes #171 
https://renji-xd.github.io/ebook-reader/
=> refactor: reversed toc flow for vertical mode

apps/web/src/lib/components/book-reader/book-reader-continuous/character-stats-calculator.ts
=> fix: handle text nodes with zero px for char count

apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte, apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte, apps/web/src/routes/+layout.svelte
=> fix: delay content processing after font load

README.md, apps/web/src/lib/components/book-card/book-manager-header.svelte, apps/web/src/lib/data/sort-types.ts, apps/web/src/lib/data/store.ts, apps/web/src/routes/manage/+page.svelte
=> feat: add custom sort

.prettierrc.cjs, apps/web/src/lib/functions/file-loaders/epub/extract-epub.ts, apps/web/src/lib/functions/file-loaders/epub/generate-epub-html.ts, apps/web/src/lib/functions/file-loaders/epub/generate-epub-style-sheet.ts, apps/web/src/lib/functions/file-loaders/epub/get-epub-cover-image-filename.ts, apps/web/src/lib/functions/file-loaders/epub/load-epub.ts, apps/web/src/lib/functions/file-loaders/epub/types.ts
=> fix: handle epub files with opf prefix

README.md
=> chore: add progress explanation

README.md, apps/web/src/lib/components/book-card/book-manager-header.svelte, apps/web/src/lib/functions/file-loaders/txt/extract-txt.ts, apps/web/src/lib/functions/file-loaders/txt/generate-txt-html.ts, apps/web/src/lib/functions/file-loaders/txt/load-txt.ts, apps/web/src/lib/functions/replication/replicator.ts, apps/web/src/routes/manage/+page.svelte
=> feat: add basic support for plain text

apps/web/src/lib/components/book-reader/book-reading-tracker/book-reading-tracker.svelte, apps/web/src/lib/components/log-report-dialog.svelte, apps/web/src/lib/components/settings/settings-reading-goals-merge.svelte, apps/web/src/lib/components/statistics/statistics-heatmap/statistics-heatmap.svelte, apps/web/src/lib/data/reading-goal.ts, apps/web/src/lib/functions/statistic-util.ts
=> fix: adjust date parsing to ignore timezones

README.md, apps/web/Dockerfile
=> chore: update docker node version and pnpm command

apps/web/src/routes/b/+page.svelte
=> fix: ensure proper context without sync

apps/web/src/lib/components/storage-unlock.svelte
=> feat: autofocus password input & enter keybind

apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte, apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte, apps/web/src/lib/components/book-reader/reactive-elements.ts, apps/web/src/lib/components/book-reader/styles.scss, apps/web/src/lib/components/settings/settings-content.svelte, apps/web/src/lib/data/furigana-style.ts
=> feat: hide furigana style option

apps/web/src/lib/data/storage/handler/gdrive-handler.ts
=> fix: request higher resolution on gdrive thumbnails

apps/web/src/lib/components/book-reader/book-reader.svelte
=> fix: don't render blur listener

apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte, apps/web/src/lib/components/book-reader/book-reader.svelte, apps/web/src/lib/components/settings/settings-content.svelte, apps/web/src/lib/data/store.ts, apps/web/src/routes/settings/+page.svelte
=> feat: add screen lock option

apps/web/src/lib/components/book-reader/book-reader-header.svelte, apps/web/src/lib/components/merged-header-icon/merged-entries.ts, apps/web/src/lib/components/number-dialog.svelte, apps/web/src/routes/b/+page.svelte
Closes #350.
This approach of creating a fake "bookmark" to jump to is admittedly a little janky; the better solution would probably be to refactor the "jump to position" code outside of the bookmark manager.
=> feat: jump to character position

apps/web/src/lib/functions/file-loaders/epub/extract-epub.ts, apps/web/src/lib/functions/file-loaders/epub/generate-epub-html.ts, apps/web/src/lib/functions/file-loaders/epub/load-epub.ts, eslint.config.js
=> fix: normalize paths for blob content in html

apps/web/src/lib/functions/file-loaders/epub/load-epub.ts
=> fix: handle list of titles in metadata

apps/web/src/lib/components/book-reader/book-reader-continuous/character-stats-calculator.ts, apps/web/src/lib/components/book-reader/book-reader-paginated/section-character-stats-calculator.ts, apps/web/src/lib/components/book-reader/book-reading-tracker/book-reading-tracker-menu.svelte, apps/web/src/lib/components/book-reader/book-reading-tracker/book-reading-tracker.svelte, apps/web/src/routes/b/+page.svelte
=> feat: time to finish chapter

apps/web/src/lib/components/book-reader/book-toc/book-toc.svelte, apps/web/src/lib/components/settings/settings-content.svelte, apps/web/src/lib/components/statistics/statistics-content.svelte, apps/web/src/routes/b/+page.svelte, apps/web/src/routes/manage/+page.svelte
=> fix: dismiss dialogs on component unrender

apps/web/src/lib/components/book-reader/styles.scss, apps/web/src/lib/functions/file-loaders/epub/generate-epub-html.ts
=> fix: force no margin for pages without text content

apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte, apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte
=> fix: adjust scrolling on resize
