ttu-ttu/ebook-reader

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/ebook-display-manager.service.ts
- src/app/reader/reader.component.ts
- src/app/utils/html-fixer.ts
Adds Support for Selection of multiple Files and Directories (Desktop Only).
Open from #2:
- Are the exchanged Icons ok
- Keep Progress Color as is or replace with which Value
Latest Example Visuals: https://imgur.com/a/aRLzWkf
Should also fix #7 and unloading the overlay accordingly + an issue I saw on refold today that you are able to select other files than htmlz / epub on mobile based on your filepicker / android.
Please also not the changes in the reader component and html-fixer. Adding inplace HTML Elements still triggers Validations and therefore ttu: will throw as unknown schema for normal pages which especially for adding a directory tree is verbose. Not a direct impact for a normal User but less red is always good ;)  I therefore replaced it with a 1x1 px base64 gif while …
> [feature] #2 multi file and directory selection added

- src/app/reader/reader.component.scss
Mobile browsers (both Chrome and Firefox for Android) report the height of the entire screen as the viewport height since the browser chrome gets hidden when you scroll.
However, since you can't vertically scroll in the reader, the browser chrome remains visible and the viewport height reported is higher than what is actually visible, resulting in the top and bottom "margins" being messed up as in the picture below:
Using `%` in calculations rather than `vh` seems to be a more robust way for calculating height.
> Use % instead of vh to determine height

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
Mobile browsers for some reason don't let the user toggle fullscreen, so the only way for a webpage to go fullscreen on mobile is for the webpage to provide the functionality.
I've added an icon on the left side that toggles fullscreen using the Fullscreen API:
The button will be hidden on browsers that don't support the Fullscreen API like Safari.
I'm happy to move the fullscreen button into Settings if we don't want it to take up space on the main screen.
> Add in button to toggle fullscreen

- src/app/settings-dialog/settings-dialog.component.scss
The settings dialog is not very usable if the page does not have enough vertical height.
This change restricts the maximum vertical height of the dialog and makes the dialog scrollable when needed.
> Restrict height of Settings and make scrollable for small screens

- src/app/ebook-display-manager.service.ts
- src/app/utils/local-storage-utils.ts
Extracted out common code for creating BehaviorSubjects that are backed by LocalStorage into utility functions.
This is in preparation for a change that I will be making to add in tooltips + a setting to toggle them.
> Refactor to simplify creation of local storage backed BehaviorSubjects.

- src/app/utils/file-loaders/epub/generate-epub-html.ts
On Importing epubs only the body content will be transefered which breaks links refering to ids set on the body.
Pr checks for an existing id on the body and if existing will prepend a helper element before the actual text content to allow navigating from the inbook toc
> fix: fix broken links for epubs using anchors on the body tag

- apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte
I noticed there are quite a few breaks inside elements across a page (especially on mobile)
This attribute will not fix all but should lower down the amount of such occurences
> minimze element breaks for paginated view

- apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte
- apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte
- apps/web/src/lib/components/book-reader/book-reader.svelte
- apps/web/src/lib/components/book-reader/reactive-elements.ts
- apps/web/src/lib/components/book-reader/styles.scss
- apps/web/src/lib/components/form-field/form-field.svelte
- apps/web/src/lib/components/settings/settings-content.svelte
- apps/web/src/lib/components/settings/settings-item-group.svelte
- apps/web/src/lib/data/furigana-style.ts
- apps/web/src/lib/data/theme-option.ts
- apps/web/src/routes/settings/index.svelte
- apps/web/tailwind.config.cjs
Includes following changes
- Responsive Column Layout for settings view (1-3 columns) and order a bit rearranged
- I read often about people disliking the glow effect on hidden furigana for dark themes - i aligned the opacity to the light themes and add a pointer cursor as additional aid
- New Option Value for Furigana style which is a on click toggle instead of hover (should solve #20 i guess)
deployed on a demo branch : https://renji-xd.github.io/ebook-reader
> feat: toggle furigana display and settings view rearrangement

- apps/web/src/lib/data/internal/writable-storage-subject.ts
There are no real validations on the settings which allows e. g. to have null for number settings.
Some code handles it, some not - e. g. the continuous scrolling for page up/down is breaking when a page is reloaded with null as value for the firstDimensionMargin.
PR writes back the defaultvalue in the writeable storage in case of undefined values
> fix: write back default value for storage

- apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte
- apps/web/src/lib/components/book-reader/book-reader-continuous/bookmark-manager-continuous.ts
- apps/web/src/lib/components/book-reader/book-reader-continuous/character-stats-calculator.ts
currently the bookmark position and character calculation ignores any configured margin in the continous mode.
Adding it into their calculations may have a better behavior 
see also https://renji-xd.github.io/ebook-reader/
> fix: include configured margin for bookmark and character stats

- apps/web/src/lib/components/book-reader/book-toc/book-toc.svelte
Currently backdrop of dialogManager stays open for the Case in which the toc is closed by its close icon
https://renji-xd.github.io/ebook-reader/manage
> fix: close backdrop of dialogManager properly

- apps/web/src/lib/components/book-reader/book-reader-paginated/book-reader-paginated.svelte
I opened an issue a couple of days ago about this problem and I think this is a fix for it.
Details can be found here: https://github.com/ttu-ttu/ebook-reader/issues/170
I added the attribute `column-width` to `.book-content-container` and I set it to `auto` when the columns are more than one and to the width of the page if there is only one column. This fixes a problem that only happens on mobile ios when `column-count` is set to value `1`. This bug makes the page load vertically instead of horizontally causing the reader to be unusable, since vertical scrolling is disabled.
I found the solution here: https://stackoverflow.com/questions/71319077/columns-or-column-count-1-not-working-safari .
I tested it and it works both on mobile and on chrome browser on pc.
> fix: Fixed incorrect page rendering in horizontal paginated mode on ios.

- README.md
- apps/web/src/lib/components/button-toggle-group/button-toggle-group.svelte
- apps/web/src/lib/components/button-toggle-group/toggle-option.ts
- apps/web/src/lib/components/settings/settings-content.svelte
- apps/web/src/lib/components/settings/settings-header.svelte
- apps/web/src/lib/components/settings/settings-item-group.svelte
- apps/web/src/routes/settings/index.svelte
Amount of Settings are growing and there will potentially also be list like data for backlog items like timer, notes etc.
Some of them may be separate pages but for some it may make sense to keep it in settings context. PR adds a tab like UX in order to lower the overload / scrolling of a one single screen.
Also adds background color for active items of settings groups + thicker border for the theme group which could close potentially #163  
Also added a Section in the Readme to explain storage limits etc. for user awareness.
https://renji-xd.github.io/ebook-reader/settings
https://github.com/Renji-XD/ebook-reader/tree/reader_demo_svelte
> refactor: tabbed like settings view and background color for active

- README.md
- apps/web/src/lib/components/book-card/book-card-list.svelte
- apps/web/src/lib/components/book-card/book-card-props.ts
- apps/web/src/lib/components/book-reader/book-reader-continuous/bookmark-manager-continuous.ts
- apps/web/src/lib/components/book-reader/book-reader-paginated/bookmark-manager-paginated.ts
- apps/web/src/lib/data/database/books-db/database.service.ts
- apps/web/src/lib/data/database/books-db/versions/v2/upgrade.ts
- apps/web/src/lib/data/database/books-db/versions/v3/books-db-v3.ts
- apps/web/src/lib/data/storage-manager/browser-handler.ts
- apps/web/src/lib/functions/file-loaders/epub/load-epub.ts
- apps/web/src/lib/functions/file-loaders/htmlz/load-htmlz.ts
- apps/web/src/lib/functions/replication/import-replication.ts
- apps/web/src/routes/b/index.svelte
- apps/web/src/routes/manage/index.svelte
PR add timestamps for adding/opening/bookmarking Books and adds sorting to the Manager View (last open > last added > old data). On Top there is a new info Icon on Book Selection which exposes the Data to User as local Datetime String via Popover.
Data can potentially be also used later for simple import/export diff options or similar
https://renji-xd.github.io/ebook-reader/
> refactor: add book timestamps and sort order

- apps/web/src/lib/data/database/books-db/database.service.ts
- apps/web/src/lib/data/fullscreen-manager.ts
- apps/web/tsconfig.json
which enforces different writing style due to esnext compile target
> fix: avoid runtime error after vite 3.14

- apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte
i think this fixes #181 
reproduceable with current reader site either by minimizing the tab before book is loaded or while resizing it forth and back - book will be on start even if there is a bookmark set.
fix on https://renji-xd.github.io/ebook-reader/manage (you can ignore the export - i did not reverted the wip changes)
> Fix resize bookmark

- README.md
- docker-compose.yml
- Changed the default port of the container, because it was currently using the default port for proxies, which was causing conflict with proxy applications like burpsuite.
- Added new command to make the container always restart if stopped unexpectedly (like power outage).
I tested on my machine and it is working well on port 9010
> Update on docker-compose.yml

- apps/web/src/lib/data/store.ts
- apps/web/src/routes/b/on-keydown-reader.ts
If using the [Key Mapper](https://github.com/keymapperorg/KeyMapper) app to send keys to the reader, the `event.code` is blank for some reason while the same key is in `event.key`. So this PR fixes that to allow Key Mapper to work with ttu reader. Has been tested locally with a Pixel 6.
> Fix/Handle Keycode Possibly Being Blank

- apps/web/static/manifest.webmanifest
I was finding the existence of the status bar very annoying while using the PWA due to the difference in color to the page background, and I think most people would prefer not to have it in the way while reading.
Did test and it works.
> Set Manifest `display` to `fullscreen`

- apps/web/src/lib/functions/file-loaders/epub/generate-epub-html.ts
Currently, the `<html>` and `<body>` tags in EPUB content are discarded (aside from the `id` attribute of the `<body>` tag). I'm encountering EPUBs that have classes on these tags, and use those classes in CSS rules:
item/xhtml/p-002.xhtml:
```html
<html
xmlns="http://www.w3.org/1999/xhtml"
xmlns:epub="http://www.idpf.org/2007/ops"
xml:lang="ja"
class="vrtl"
>
<body class="p-text">
<div class="main">
...
```
item/style/style-standard.css:
```css
.hltr .start-4em   { margin-left:  4.00em; }
.vrtl .start-4em   { margin-top:  4.00em; }
```
This patch creates wrapper divs that duplicate the `class` attributes of the `<html>` and `<body>` tags to make sure EPUB stylesheets function as expected.
> fix: preserve classes on <html> and <body> tags in EPUBs

- apps/web/src/app.html
- apps/web/src/lib/components/settings/settings-content.svelte
- apps/web/src/lib/data/fonts.ts
- apps/web/src/lib/functions/book-data-loader/format-style-sheet.ts
Changes language tag from English to Japanese to make sure symbols are rendered correctly for fonts that don't have full coverage. This also fixes an issue with fallback fonts being rendered incorrectly and incorrect system fonts being chosen by the browser.
In addition to this, the default font when the font-family fields are empty has been changed to the default serif and sans-serif  fonts of the user's device. These fonts have also been added to the font menu to make it easy for the user to choose their device's system fonts.
> feat: add system fonts and change language tag

- apps/web/src/app.scss
Makes scrollbar background color transparent to universally match user themes for browsers that don't already do so (e.g. Chrome)
> fix: chrome scrollbar colors

- apps/web/src/app.scss
- apps/web/src/lib/components/book-card/book-card.svelte
Fixes a rendering issue of the book covers that occurs due to a bug in chrome that causes images that use "object-fit: cover" to become pixelated.
> fix: chrome cover rendering

- .github/renovate.json
- apps/web/package.json
- pnpm-lock.yaml
This reverts commit 0fca3902b9fd2558945f4d71c9a59f5b6fccf8fa.
svelte-gestures 5.1.0 and later are only compatible with Svelte 5.
> Revert "fix(deps): update dependency svelte-gestures to v5.1.2"
